remove comments on the test

diff --git a/daemonSet-pod-to-pod-connection-matrix.yaml b/daemonSet-pod-to-pod-connection-matrix.yaml
--- a/daemonSet-pod-to-pod-connection-matrix.yaml
+++ b/daemonSet-pod-to-pod-connection-matrix.yaml
@@ -31,15 +31,16 @@ spec:
 
 # Run the following loop to test the connections between each of the pods in the DaemonSet to each other:
 
-# for pod in $(kubectl get pod -n kube-system -l app=nginx-test --output=jsonpath={.items..metadata.name});
-# do
-#     kubectl get po $pod -n kube-system --output=jsonpath='{"\n"}{.metadata.name}{" "}{..status.podIP}{" "}{.spec.nodeName}{" "}{..status.hostIP}{"\n"}';
-#     for podip in $(kubectl get -n kube-system po -A -l app=nginx-test --output=jsonpath={..status.podIP});
-#   do
-#      kubectl exec -n kube-system -it $pod -c nginx-test -- curl -m 5 -s -o /dev/null $podip && echo "$pod can connect to $podip" || echo "$pod cannot connect to $podip";
-#   done
-# done
-
+```
+for pod in $(kubectl get pod -n kube-system -l app=nginx-test --output=jsonpath={.items..metadata.name});
+do
+    kubectl get po $pod -n kube-system --output=jsonpath='{"\n"}{.metadata.name}{" "}{..status.podIP}{" "}{.spec.nodeName}{" "}{..status.hostIP}{"\n"}';
+    for podip in $(kubectl get -n kube-system po -A -l app=nginx-test --output=jsonpath={..status.podIP});
+  do
+     kubectl exec -n kube-system -it $pod -c nginx-test -- curl -m 5 -s -o /dev/null $podip && echo "$pod can connect to $podip" || echo "$pod cannot connect to $podip";
+  done
+done
+```
 
 # Sample output:
 
